from dotenv import load_dotenv
load_dotenv()

"""
alert_writer.py
---------------
The HANDS of the drilling-npt-agent.

Takes structured NPT alerts produced by domain_agent.py (the Brain)
and persists them in two places:
  1. Local JSON file  — immediate review, debugging, field reporting
  2. Databricks Delta table — alerts ARE data, store them like data engineers do

Why Delta for drilling alerts?
  Over time the alert table becomes a queryable well history:
  - "How many CRITICAL alerts in the tangent section?"
  - "Which NPT type appeared most in this well?"
  - "Was twist-off risk flagged before the actual incident?"

  That's the audit trail that makes post-well reviews possible
  and feeds future ML training data for the industry.

Two Delta tables:
  npt_alerts       — one row per alert (the incident log)
  npt_run_summary  — one row per agent run (the session summary)
"""

import os
import json
import requests
import time
from datetime import datetime, timezone
from databricks.sdk import WorkspaceClient

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

REPORT_DIR        = "reports"
ALERTS_TABLE      = "workspace.drilling.npt_alerts"
SUMMARY_TABLE     = "workspace.drilling.npt_run_summary"


# ---------------------------------------------------------------------------
# Databricks helpers
# ---------------------------------------------------------------------------

def _get_client():
    return WorkspaceClient()


def _get_warehouse_id(client) -> str:
    http_path = os.environ.get("DATABRICKS_HTTP_PATH", "")
    if http_path:
        return http_path.strip("/").split("/")[-1]
    warehouses = client.warehouses.list()
    for wh in warehouses:
        if wh.state.value in ("RUNNING", "IDLE"):
            return wh.id
    raise RuntimeError("No running SQL warehouse found.")


def _execute_sql(client, sql: str, warehouse_id: str):
    host    = client.config.host
    token   = client.config.token
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type":  "application/json",
    }
    resp = requests.post(
        f"{host}/api/2.0/sql/statements",
        headers=headers,
        json={
            "statement":       sql,
            "warehouse_id":    warehouse_id,
            "wait_timeout":    "30s",
            "on_wait_timeout": "CONTINUE",
        },
    )
    resp.raise_for_status()
    payload      = resp.json()
    statement_id = payload["statement_id"]

    for _ in range(30):
        state = payload.get("status", {}).get("state", "")
        if state in ("SUCCEEDED", "FAILED", "CANCELED", "CLOSED"):
            break
        time.sleep(2)
        poll = requests.get(
            f"{host}/api/2.0/sql/statements/{statement_id}",
            headers=headers,
        )
        poll.raise_for_status()
        payload = poll.json()

    state = payload.get("status", {}).get("state")
    if state != "SUCCEEDED":
        error = payload.get("status", {}).get("error", {})
        raise RuntimeError(f"SQL failed [{state}]: {error.get('message', 'unknown')}")


# ---------------------------------------------------------------------------
# Table creation
# ---------------------------------------------------------------------------

def _ensure_tables_exist(client, warehouse_id: str):
    """Create both Delta tables if they don't exist."""

    alerts_sql = f"""
    CREATE TABLE IF NOT EXISTS {ALERTS_TABLE} (
        alert_id                STRING,
        run_id                  STRING,
        timestamp               TIMESTAMP,
        depth_m                 DOUBLE,
        operation_state         STRING,
        alert_severity          STRING,
        npt_type                STRING,
        confidence              STRING,
        intervention_window     STRING,
        primary_diagnosis       STRING,
        matching_signals        STRING,
        immediate_actions       STRING,
        parameters_to_watch     STRING,
        estimated_cost          STRING,
        driller_note            STRING,
        alternative_explanation STRING,
        ground_truth_label      STRING,
        ground_truth_phase      STRING,
        generated_at            TIMESTAMP
    )
    USING DELTA
    COMMENT 'NPT alerts generated by drilling-npt-agent. One row per alert. Queryable well incident history.'
    """

    summary_sql = f"""
    CREATE TABLE IF NOT EXISTS {SUMMARY_TABLE} (
        run_id              STRING,
        well_name           STRING,
        run_started_at      TIMESTAMP,
        run_completed_at    TIMESTAMP,
        duration_sec        DOUBLE,
        windows_analyzed    INT,
        alerts_critical     INT,
        alerts_high         INT,
        alerts_medium       INT,
        alerts_low          INT,
        alerts_monitor      INT,
        npt_types_detected  STRING,
        depth_range_m       STRING
    )
    USING DELTA
    COMMENT 'Summary of each drilling-npt-agent run. One row per session.'
    """

    _execute_sql(client, alerts_sql.strip(), warehouse_id)
    print(f"   ✅ Delta table ready: {ALERTS_TABLE}")
    _execute_sql(client, summary_sql.strip(), warehouse_id)
    print(f"   ✅ Delta table ready: {SUMMARY_TABLE}")


# ---------------------------------------------------------------------------
# Writer 1 — Local JSON file
# ---------------------------------------------------------------------------

def write_to_file(alerts: list, run_id: str) -> str:
    """Write all alerts from a run to a single timestamped JSON file."""
    os.makedirs(REPORT_DIR, exist_ok=True)
    filename = f"{REPORT_DIR}/{run_id}.json"
    payload  = {
        "run_id":       run_id,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "alert_count":  len(alerts),
        "alerts":       alerts,
    }
    with open(filename, "w") as f:
        json.dump(payload, f, indent=2, default=str)
    print(f"   📄 Alerts written to file: {filename}")
    return filename


# ---------------------------------------------------------------------------
# Writer 2 — Databricks Delta table
# ---------------------------------------------------------------------------

def _esc(val) -> str:
    return str(val).replace("'", "\\'") if val is not None else ""


def _fmt_ts(ts_str: str) -> str:
    try:
        ts = str(ts_str)[:19].replace("T", " ")
        return ts
    except Exception:
        return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")


def write_alerts_to_delta(alerts: list, run_id: str, client, warehouse_id: str):
    """Insert each alert as one row into npt_alerts Delta table."""
    for alert in alerts:
        gt        = alert.get("ground_truth", {})
        gen_at    = _fmt_ts(alert.get("generated_at",
                    datetime.now(timezone.utc).isoformat()))
        ts        = _fmt_ts(alert.get("timestamp",
                    datetime.now(timezone.utc).isoformat()))

        sql = f"""
        INSERT INTO {ALERTS_TABLE} VALUES (
            '{_esc(alert.get("alert_id", ""))}',
            '{_esc(run_id)}',
            TIMESTAMP '{ts}',
            {alert.get("depth_m") or 0.0},
            '{_esc(alert.get("operation_state", ""))}',
            '{_esc(alert.get("alert_severity", ""))}',
            '{_esc(alert.get("npt_type", ""))}',
            '{_esc(alert.get("confidence", ""))}',
            '{_esc(alert.get("intervention_window", ""))}',
            '{_esc(alert.get("primary_diagnosis", ""))}',
            '{_esc(json.dumps(alert.get("matching_signals", [])))}',
            '{_esc(json.dumps(alert.get("immediate_actions", [])))}',
            '{_esc(json.dumps(alert.get("parameters_to_watch", [])))}',
            '{_esc(alert.get("estimated_cost", ""))}',
            '{_esc(alert.get("driller_note", ""))}',
            '{_esc(alert.get("alternative_explanation", ""))}',
            '{_esc(gt.get("npt_label", ""))}',
            '{_esc(gt.get("npt_phase", ""))}',
            TIMESTAMP '{gen_at}'
        )
        """
        _execute_sql(client, sql.strip(), warehouse_id)
        severity = alert.get("alert_severity", "")
        npt_type = alert.get("npt_type", "")
        print(f"   ✅ [{severity}] {npt_type} at {alert.get('depth_m')}m → {ALERTS_TABLE}")


def write_summary_to_delta(run_id: str, alerts: list, well_name: str,
                           started_at: str, completed_at: str,
                           duration_sec: float, client, warehouse_id: str):
    """Insert one summary row into npt_run_summary Delta table."""
    severity_counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "MONITOR": 0}
    npt_types       = set()
    depths          = [a.get("depth_m", 0) for a in alerts if a.get("depth_m")]

    for alert in alerts:
        sev = alert.get("alert_severity", "MONITOR")
        if sev in severity_counts:
            severity_counts[sev] += 1
        npt_type = alert.get("npt_type", "")
        if npt_type and npt_type != "NORMAL":
            npt_types.add(npt_type)

    depth_range = (f"{min(depths):.0f}m – {max(depths):.0f}m"
                   if depths else "unknown")

    sql = f"""
    INSERT INTO {SUMMARY_TABLE} VALUES (
        '{_esc(run_id)}',
        '{_esc(well_name)}',
        TIMESTAMP '{_fmt_ts(started_at)}',
        TIMESTAMP '{_fmt_ts(completed_at)}',
        {duration_sec},
        {len(alerts)},
        {severity_counts["CRITICAL"]},
        {severity_counts["HIGH"]},
        {severity_counts["MEDIUM"]},
        {severity_counts["LOW"]},
        {severity_counts["MONITOR"]},
        '{_esc(", ".join(sorted(npt_types)))}',
        '{_esc(depth_range)}'
    )
    """
    _execute_sql(client, sql.strip(), warehouse_id)
    print(f"   ✅ Run summary inserted → {SUMMARY_TABLE}")


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def write_alerts(alerts: list, run_id: str, well_name: str = "SYNTHETIC-WELL-001",
                 started_at: str = None, completed_at: str = None,
                 duration_sec: float = 0.0):
    """
    Persist all alerts from an agent run to file + Delta tables.
    Called by run_agent.py after the full analysis loop completes.
    """
    print("\n✍️  Writing NPT alerts...")

    if not started_at:
        started_at = datetime.now(timezone.utc).isoformat()
    if not completed_at:
        completed_at = datetime.now(timezone.utc).isoformat()

    # 1. Local file — always first
    file_path = write_to_file(alerts, run_id)

    # 2. Delta tables
    try:
        print(f"\n   🔌 Connecting to Databricks...")
        client       = _get_client()
        warehouse_id = _get_warehouse_id(client)
        _ensure_tables_exist(client, warehouse_id)
        write_alerts_to_delta(alerts, run_id, client, warehouse_id)
        write_summary_to_delta(run_id, alerts, well_name, started_at,
                               completed_at, duration_sec, client, warehouse_id)
    except Exception as e:
        print(f"   ⚠️  Delta write failed (file report still saved): {e}")

    # Summary
    critical = sum(1 for a in alerts if a.get("alert_severity") == "CRITICAL")
    high     = sum(1 for a in alerts if a.get("alert_severity") == "HIGH")
    medium   = sum(1 for a in alerts if a.get("alert_severity") == "MEDIUM")

    print(f"\n✅ Alerts persisted successfully.")
    print(f"   Total alerts : {len(alerts)}")
    print(f"   CRITICAL     : {critical}")
    print(f"   HIGH         : {high}")
    print(f"   MEDIUM       : {medium}")
    print(f"   File         : {file_path}")
    print(f"   Delta tables : {ALERTS_TABLE}")
    print(f"                  {SUMMARY_TABLE}")


if __name__ == "__main__":
    # Quick test with dummy alert
    dummy_alerts = [
        {
            "alert_id":            "NPT-0199",
            "timestamp":           "2026-04-01 12:38:00",
            "depth_m":             2352.9,
            "operation_state":     "DRILLING",
            "alert_severity":      "MEDIUM",
            "npt_type":            "STUCK_PIPE_RISK",
            "confidence":          "MEDIUM",
            "intervention_window": "OPEN",
            "primary_diagnosis":   "Test alert — early stuck pipe risk signature",
            "matching_signals":    ["hookload increasing", "rop declining"],
            "immediate_actions":   ["Reduce WOB", "Increase flow rate"],
            "parameters_to_watch": ["delta_hookload_tons", "torque_knm"],
            "estimated_cost":      "$500K–$2M if ignored",
            "driller_note":        "Test note — back off WOB and monitor.",
            "alternative_explanation": "Could be formation change",
            "ground_truth":        {"npt_label": "STUCK_PIPE_RISK", "npt_phase": "EARLY"},
            "generated_at":        datetime.now(timezone.utc).isoformat(),
        }
    ]

    run_id = f"npt-test-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M%S')}"
    write_alerts(dummy_alerts, run_id)
